# Generated by Django 4.2.2 on 2023-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_auto_20230613_1133"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="имя клиента")),
                (
                    "mail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                ("message", models.TextField(verbose_name="заявка")),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "проект", "verbose_name_plural": "проекты"},
        ),
    ]
