# Generated by Django 4.2.2 on 2023-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_userappeal_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userappeal",
            name="mail",
            field=models.EmailField(max_length=254, verbose_name="почта"),
        ),
    ]
